class Failure {
  final String message;
  const Failure([
    this.message = 'An unexpected error occured, please try again later.',
  ]);
}
